services:
  - type: web
    name: facial-auth-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18